// GENERATED FILE — DO NOT EDIT.
// Produced by scripts/generate_protocol.py from the app-server JSON Schema
// (`codex app-server generate-json-schema`). Regenerate instead of editing.
// Notification dispatch table.

@file:Suppress("unused", "RedundantVisibilityModifier", "LongParameterList", "MaxLineLength")
@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package dev.kodachi.protocol

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/**
 * Every server notification method this protocol version defines, mapped to the
 * serializer for its payload. Methods absent here decode to [UnknownNotification].
 */
internal val NotificationSerializers: Map<String, KSerializer<out CodexNotification>> = mapOf(
    "error" to ErrorNotification.serializer(),
    "thread/started" to ThreadStartedNotification.serializer(),
    "thread/status/changed" to ThreadStatusChangedNotification.serializer(),
    "thread/archived" to ThreadArchivedNotification.serializer(),
    "thread/deleted" to ThreadDeletedNotification.serializer(),
    "thread/unarchived" to ThreadUnarchivedNotification.serializer(),
    "thread/closed" to ThreadClosedNotification.serializer(),
    "skills/changed" to SkillsChangedNotification.serializer(),
    "thread/name/updated" to ThreadNameUpdatedNotification.serializer(),
    "thread/goal/updated" to ThreadGoalUpdatedNotification.serializer(),
    "thread/goal/cleared" to ThreadGoalClearedNotification.serializer(),
    "thread/environment/connected" to EnvironmentConnectionNotification.serializer(),
    "thread/environment/disconnected" to EnvironmentConnectionNotification.serializer(),
    "thread/settings/updated" to ThreadSettingsUpdatedNotification.serializer(),
    "thread/tokenUsage/updated" to ThreadTokenUsageUpdatedNotification.serializer(),
    "turn/started" to TurnStartedNotification.serializer(),
    "hook/started" to HookStartedNotification.serializer(),
    "turn/completed" to TurnCompletedNotification.serializer(),
    "hook/completed" to HookCompletedNotification.serializer(),
    "turn/diff/updated" to TurnDiffUpdatedNotification.serializer(),
    "turn/plan/updated" to TurnPlanUpdatedNotification.serializer(),
    "item/started" to ItemStartedNotification.serializer(),
    "item/autoApprovalReview/started" to ItemGuardianApprovalReviewStartedNotification.serializer(),
    "item/autoApprovalReview/completed" to ItemGuardianApprovalReviewCompletedNotification.serializer(),
    "item/completed" to ItemCompletedNotification.serializer(),
    "item/agentMessage/delta" to AgentMessageDeltaNotification.serializer(),
    "item/plan/delta" to PlanDeltaNotification.serializer(),
    "command/exec/outputDelta" to CommandExecOutputDeltaNotification.serializer(),
    "process/outputDelta" to ProcessOutputDeltaNotification.serializer(),
    "process/exited" to ProcessExitedNotification.serializer(),
    "item/commandExecution/outputDelta" to CommandExecutionOutputDeltaNotification.serializer(),
    "item/commandExecution/terminalInteraction" to TerminalInteractionNotification.serializer(),
    "item/fileChange/outputDelta" to FileChangeOutputDeltaNotification.serializer(),
    "item/fileChange/patchUpdated" to FileChangePatchUpdatedNotification.serializer(),
    "serverRequest/resolved" to ServerRequestResolvedNotification.serializer(),
    "item/mcpToolCall/progress" to McpToolCallProgressNotification.serializer(),
    "mcpServer/oauthLogin/completed" to McpServerOauthLoginCompletedNotification.serializer(),
    "mcpServer/startupStatus/updated" to McpServerStatusUpdatedNotification.serializer(),
    "account/updated" to AccountUpdatedNotification.serializer(),
    "account/rateLimits/updated" to AccountRateLimitsUpdatedNotification.serializer(),
    "app/list/updated" to AppListUpdatedNotification.serializer(),
    "remoteControl/status/changed" to RemoteControlStatusChangedNotification.serializer(),
    "externalAgentConfig/import/progress" to ExternalAgentConfigImportProgressNotification.serializer(),
    "externalAgentConfig/import/completed" to ExternalAgentConfigImportCompletedNotification.serializer(),
    "fs/changed" to FsChangedNotification.serializer(),
    "item/reasoning/summaryTextDelta" to ReasoningSummaryTextDeltaNotification.serializer(),
    "item/reasoning/summaryPartAdded" to ReasoningSummaryPartAddedNotification.serializer(),
    "item/reasoning/textDelta" to ReasoningTextDeltaNotification.serializer(),
    "thread/compacted" to ContextCompactedNotification.serializer(),
    "model/rerouted" to ModelReroutedNotification.serializer(),
    "model/verification" to ModelVerificationNotification.serializer(),
    "turn/moderationMetadata" to TurnModerationMetadataNotification.serializer(),
    "model/safetyBuffering/updated" to ModelSafetyBufferingUpdatedNotification.serializer(),
    "warning" to WarningNotification.serializer(),
    "guardianWarning" to GuardianWarningNotification.serializer(),
    "deprecationNotice" to DeprecationNoticeNotification.serializer(),
    "configWarning" to ConfigWarningNotification.serializer(),
    "fuzzyFileSearch/sessionUpdated" to FuzzyFileSearchSessionUpdatedNotification.serializer(),
    "fuzzyFileSearch/sessionCompleted" to FuzzyFileSearchSessionCompletedNotification.serializer(),
    "thread/realtime/started" to ThreadRealtimeStartedNotification.serializer(),
    "thread/realtime/itemAdded" to ThreadRealtimeItemAddedNotification.serializer(),
    "thread/realtime/transcript/delta" to ThreadRealtimeTranscriptDeltaNotification.serializer(),
    "thread/realtime/transcript/done" to ThreadRealtimeTranscriptDoneNotification.serializer(),
    "thread/realtime/outputAudio/delta" to ThreadRealtimeOutputAudioDeltaNotification.serializer(),
    "thread/realtime/sdp" to ThreadRealtimeSdpNotification.serializer(),
    "thread/realtime/error" to ThreadRealtimeErrorNotification.serializer(),
    "thread/realtime/closed" to ThreadRealtimeClosedNotification.serializer(),
    "windows/worldWritableWarning" to WindowsWorldWritableWarningNotification.serializer(),
    "windowsSandbox/setupCompleted" to WindowsSandboxSetupCompletedNotification.serializer(),
    "account/login/completed" to AccountLoginCompletedNotification.serializer(),
)

/** Wire method names for every server notification, for tests and diagnostics. */
public val ALL_SERVER_NOTIFICATION_METHODS: List<String> = listOf(
    "error",
    "thread/started",
    "thread/status/changed",
    "thread/archived",
    "thread/deleted",
    "thread/unarchived",
    "thread/closed",
    "skills/changed",
    "thread/name/updated",
    "thread/goal/updated",
    "thread/goal/cleared",
    "thread/environment/connected",
    "thread/environment/disconnected",
    "thread/settings/updated",
    "thread/tokenUsage/updated",
    "turn/started",
    "hook/started",
    "turn/completed",
    "hook/completed",
    "turn/diff/updated",
    "turn/plan/updated",
    "item/started",
    "item/autoApprovalReview/started",
    "item/autoApprovalReview/completed",
    "item/completed",
    "item/agentMessage/delta",
    "item/plan/delta",
    "command/exec/outputDelta",
    "process/outputDelta",
    "process/exited",
    "item/commandExecution/outputDelta",
    "item/commandExecution/terminalInteraction",
    "item/fileChange/outputDelta",
    "item/fileChange/patchUpdated",
    "serverRequest/resolved",
    "item/mcpToolCall/progress",
    "mcpServer/oauthLogin/completed",
    "mcpServer/startupStatus/updated",
    "account/updated",
    "account/rateLimits/updated",
    "app/list/updated",
    "remoteControl/status/changed",
    "externalAgentConfig/import/progress",
    "externalAgentConfig/import/completed",
    "fs/changed",
    "item/reasoning/summaryTextDelta",
    "item/reasoning/summaryPartAdded",
    "item/reasoning/textDelta",
    "thread/compacted",
    "model/rerouted",
    "model/verification",
    "turn/moderationMetadata",
    "model/safetyBuffering/updated",
    "warning",
    "guardianWarning",
    "deprecationNotice",
    "configWarning",
    "fuzzyFileSearch/sessionUpdated",
    "fuzzyFileSearch/sessionCompleted",
    "thread/realtime/started",
    "thread/realtime/itemAdded",
    "thread/realtime/transcript/delta",
    "thread/realtime/transcript/done",
    "thread/realtime/outputAudio/delta",
    "thread/realtime/sdp",
    "thread/realtime/error",
    "thread/realtime/closed",
    "windows/worldWritableWarning",
    "windowsSandbox/setupCompleted",
    "account/login/completed",
)
